import type { Movie } from '../interfaces/interfaces';


export const movies: Movie[] = [
  {
    id: 1001,
    title: "Shadows of Tomorrow",
    adult: false,
    backdrop_path: "/backdrops/shadows_tomorrow.jpg",
    genre_ids: [12, 878, 53],
    original_language: "en",
    original_title: "Shadows of Tomorrow",
    overview: "When humanity reaches its limit, the next leap begins.",
    popularity: 58.3,
    poster_path: "/posters/shadows_tomorrow.jpg",
    release_date: "2025-03-14",
    video: false,
    vote_average: 7.2,
    vote_count: 834,
  },
  {
    id: 1002,
    title: "Whispering Winds",
    adult: false,
    backdrop_path: "/backdrops/whispering_winds.jpg",
    genre_ids: [18, 10749],
    original_language: "fr",
    original_title: "Les Vents Murmurants",
    overview: "A love story carried by the wind across continents.",
    popularity: 29.9,
    poster_path: "/posters/whispering_winds.jpg",
    release_date: "2024-11-22",
    video: false,
    vote_average: 6.8,
    vote_count: 412,
  },
  {
    id: 1003,
    title: "Cyber Siege",
    adult: false,
    backdrop_path: "/backdrops/cyber_siege.jpg",
    genre_ids: [28, 53],
    original_language: "en",
    original_title: "Cyber Siege",
    overview: "A hacker-turned-hero must defend the city from digital destruction.",
    popularity: 74.1,
    poster_path: "/posters/cyber_siege.jpg",
    release_date: "2025-01-10",
    video: false,
    vote_average: 7.9,
    vote_count: 1023,
  },
  {
    id: 1004,
    title: "Midnight Garden",
    adult: false,
    backdrop_path: "/backdrops/midnight_garden.jpg",
    genre_ids: [14, 18],
    original_language: "en",
    original_title: "Midnight Garden",
    overview: "In a secret garden at midnight, everything becomes possible.",
    popularity: 19.7,
    poster_path: "/posters/midnight_garden.jpg",
    release_date: "2023-09-05",
    video: false,
    vote_average: 6.2,
    vote_count: 274,
  },
  {
    id: 1005,
    title: "Rogue Planet",
    adult: false,
    backdrop_path: "/backdrops/rogue_planet.jpg",
    genre_ids: [12, 878],
    original_language: "en",
    original_title: "Rogue Planet",
    overview: "Stranded on a wild planet, they fight for survival and hope.",
    popularity: 64.8,
    poster_path: "/posters/rogue_planet.jpg",
    release_date: "2024-06-17",
    video: false,
    vote_average: 7.4,
    vote_count: 689,
  },
  {
    id: 1006,
    title: "Echoes of Silence",
    adult: false,
    backdrop_path: "/backdrops/echoes_silence.jpg",
    genre_ids: [27, 53],
    original_language: "en",
    original_title: "Echoes of Silence",
    overview: "A haunted house and the echoes that never leave.",
    popularity: 22.3,
    poster_path: "/posters/echoes_silence.jpg",
    release_date: "2023-10-31",
    video: false,
    vote_average: 6.1,
    vote_count: 311,
  },
  {
    id: 1007,
    title: "The Final Score",
    adult: false,
    backdrop_path: "/backdrops/final_score.jpg",
    genre_ids: [35, 18],
    original_language: "en",
    original_title: "The Final Score",
    overview: "One last game to win more than the championship.",
    popularity: 45.5,
    poster_path: "/posters/final_score.jpg",
    release_date: "2025-04-20",
    video: false,
    vote_average: 7.0,
    vote_count: 523,
  },
  {
    id: 1008,
    title: "Fire & Ice",
    adult: false,
    backdrop_path: "/backdrops/fire_ice.jpg",
    genre_ids: [12, 14, 10751],
    original_language: "en",
    original_title: "Fire & Ice",
    overview: "Mythical beasts clash in the frozen lands as fire rises.",
    popularity: 56.1,
    poster_path: "/posters/fire_ice.jpg",
    release_date: "2024-12-12",
    video: false,
    vote_average: 7.6,
    vote_count: 758,
  },
  {
    id: 1009,
    title: "Urban Shadows",
    adult: true,
    backdrop_path: "/backdrops/urban_shadows.jpg",
    genre_ids: [80, 53],
    original_language: "en",
    original_title: "Urban Shadows",
    overview: "Inside the crime-web of the city’s darkest corners.",
    popularity: 33.4,
    poster_path: "/posters/urban_shadows.jpg",
    release_date: "2023-08-15",
    video: false,
    vote_average: 5.9,
    vote_count: 210,
  },
  {
    id: 1010,
    title: "Solar Dawn",
    adult: false,
    backdrop_path: "/backdrops/solar_dawn.jpg",
    genre_ids: [878, 28],
    original_language: "en",
    original_title: "Solar Dawn",
    overview: "A new era begins as the sun rises on a distant world.",
    popularity: 68.2,
    poster_path: "/posters/solar_dawn.jpg",
    release_date: "2024-02-22",
    video: false,
    vote_average: 7.5,
    vote_count: 845,
  },
];

