import type { Movie, MovieDetails, TrendingMovie } from '../interfaces/interfaces';


export const movies: Movie[] = [
  {
    id: 1001,
    title: "Shadows of Tomorrow",
    adult: false,
    backdrop_path: "/backdrops/shadows_tomorrow.jpg",
    genre_ids: [12, 878, 53],
    original_language: "en",
    original_title: "Shadows of Tomorrow",
    overview: "When humanity reaches its limit, the next leap begins.",
    popularity: 58.3,
    poster_path: "/posters/shadows_tomorrow.jpg",
    release_date: "2025-03-14",
    video: false,
    vote_average: 7.2,
    vote_count: 834,
  },
  {
    id: 1002,
    title: "Whispering Winds",
    adult: false,
    backdrop_path: "/backdrops/whispering_winds.jpg",
    genre_ids: [18, 10749],
    original_language: "fr",
    original_title: "Les Vents Murmurants",
    overview: "A love story carried by the wind across continents.",
    popularity: 29.9,
    poster_path: "/posters/whispering_winds.jpg",
    release_date: "2024-11-22",
    video: false,
    vote_average: 6.8,
    vote_count: 412,
  },
  {
    id: 1003,
    title: "Cyber Siege",
    adult: false,
    backdrop_path: "/backdrops/cyber_siege.jpg",
    genre_ids: [28, 53],
    original_language: "en",
    original_title: "Cyber Siege",
    overview: "A hacker-turned-hero must defend the city from digital destruction.",
    popularity: 74.1,
    poster_path: "/posters/cyber_siege.jpg",
    release_date: "2025-01-10",
    video: false,
    vote_average: 7.9,
    vote_count: 1023,
  },
  {
    id: 1004,
    title: "Midnight Garden",
    adult: false,
    backdrop_path: "/backdrops/midnight_garden.jpg",
    genre_ids: [14, 18],
    original_language: "en",
    original_title: "Midnight Garden",
    overview: "In a secret garden at midnight, everything becomes possible.",
    popularity: 19.7,
    poster_path: "/posters/midnight_garden.jpg",
    release_date: "2023-09-05",
    video: false,
    vote_average: 6.2,
    vote_count: 274,
  },
  {
    id: 1005,
    title: "Rogue Planet",
    adult: false,
    backdrop_path: "/backdrops/rogue_planet.jpg",
    genre_ids: [12, 878],
    original_language: "en",
    original_title: "Rogue Planet",
    overview: "Stranded on a wild planet, they fight for survival and hope.",
    popularity: 64.8,
    poster_path: "/posters/rogue_planet.jpg",
    release_date: "2024-06-17",
    video: false,
    vote_average: 7.4,
    vote_count: 689,
  },
  {
    id: 1006,
    title: "Echoes of Silence",
    adult: false,
    backdrop_path: "/backdrops/echoes_silence.jpg",
    genre_ids: [27, 53],
    original_language: "en",
    original_title: "Echoes of Silence",
    overview: "A haunted house and the echoes that never leave.",
    popularity: 22.3,
    poster_path: "/posters/echoes_silence.jpg",
    release_date: "2023-10-31",
    video: false,
    vote_average: 6.1,
    vote_count: 311,
  },
  {
    id: 1007,
    title: "The Final Score",
    adult: false,
    backdrop_path: "/backdrops/final_score.jpg",
    genre_ids: [35, 18],
    original_language: "en",
    original_title: "The Final Score",
    overview: "One last game to win more than the championship.",
    popularity: 45.5,
    poster_path: "/posters/final_score.jpg",
    release_date: "2025-04-20",
    video: false,
    vote_average: 7.0,
    vote_count: 523,
  },
  {
    id: 1008,
    title: "Fire & Ice",
    adult: false,
    backdrop_path: "/backdrops/fire_ice.jpg",
    genre_ids: [12, 14, 10751],
    original_language: "en",
    original_title: "Fire & Ice",
    overview: "Mythical beasts clash in the frozen lands as fire rises.",
    popularity: 56.1,
    poster_path: "/posters/fire_ice.jpg",
    release_date: "2024-12-12",
    video: false,
    vote_average: 7.6,
    vote_count: 758,
  },
  {
    id: 1009,
    title: "Urban Shadows",
    adult: true,
    backdrop_path: "/backdrops/urban_shadows.jpg",
    genre_ids: [80, 53],
    original_language: "en",
    original_title: "Urban Shadows",
    overview: "Inside the crime-web of the city’s darkest corners.",
    popularity: 33.4,
    poster_path: "/posters/urban_shadows.jpg",
    release_date: "2023-08-15",
    video: false,
    vote_average: 5.9,
    vote_count: 210,
  },
  {
    id: 1010,
    title: "Solar Dawn",
    adult: false,
    backdrop_path: "/backdrops/solar_dawn.jpg",
    genre_ids: [878, 28],
    original_language: "en",
    original_title: "Solar Dawn",
    overview: "A new era begins as the sun rises on a distant world.",
    popularity: 68.2,
    poster_path: "/posters/solar_dawn.jpg",
    release_date: "2024-02-22",
    video: false,
    vote_average: 7.5,
    vote_count: 845,
  },
];

export const trendingMovies: TrendingMovie[] = [
  {
    searchTerm: "adventure",
    movie_id: 1001,
    title: "Shadows of Tomorrow",
    count: 190,
    poster_url: "https://images.example.com/posters/shadows_tomorrow.jpg",
  },
  {
    searchTerm: "romance",
    movie_id: 1002,
    title: "Whispering Winds",
    count: 145,
    poster_url: "https://images.example.com/posters/whispering_winds.jpg",
  },
  {
    searchTerm: "sci-fi",
    movie_id: 1003,
    title: "Cyber Siege",
    count: 220,
    poster_url: "https://images.example.com/posters/cyber_siege.jpg",
  },
  {
    searchTerm: "fantasy",
    movie_id: 1008,
    title: "Fire & Ice",
    count: 180,
    poster_url: "https://images.example.com/posters/fire_ice.jpg",
  },
  {
    searchTerm: "thriller",
    movie_id: 1006,
    title: "Echoes of Silence",
    count: 95,
    poster_url: "https://images.example.com/posters/echoes_silence.jpg",
  },
  {
    searchTerm: "sports",
    movie_id: 1007,
    title: "The Final Score",
    count: 130,
    poster_url: "https://images.example.com/posters/final_score.jpg",
  },
  {
    searchTerm: "crime",
    movie_id: 1009,
    title: "Urban Shadows",
    count: 70,
    poster_url: "https://images.example.com/posters/urban_shadows.jpg",
  },
  {
    searchTerm: "space",
    movie_id: 1010,
    title: "Solar Dawn",
    count: 200,
    poster_url: "https://images.example.com/posters/solar_dawn.jpg",
  },
  {
    searchTerm: "survival",
    movie_id: 1005,
    title: "Rogue Planet",
    count: 110,
    poster_url: "https://images.example.com/posters/rogue_planet.jpg",
  },
  {
    searchTerm: "mystery",
    movie_id: 1004,
    title: "Midnight Garden",
    count: 85,
    poster_url: "https://images.example.com/posters/midnight_garden.jpg",
  },
];

export const movieDetails: MovieDetails[] = [
  {
    adult: false,
    backdrop_path: "/backdrops/shadows_tomorrow.jpg",
    belongs_to_collection: {
      id: 3001,
      name: "Tomorrow Saga",
      poster_path: "/collections/tomorrow_saga.jpg",
      backdrop_path: "/collections/backdrop_tomorrow_saga.jpg",
    },
    budget: 120000000,
    genres: [
      { id: 12, name: "Adventure" },
      { id: 878, name: "Science Fiction" },
      { id: 53, name: "Thriller" },
    ],
    homepage: "https://tomorrow-saga.example.com",
    id: 1001,
    imdb_id: "tt1001001",
    original_language: "en",
    original_title: "Shadows of Tomorrow",
    overview: "When humanity reaches its limit, the next leap begins.",
    popularity: 58.3,
    poster_path: "/posters/shadows_tomorrow.jpg",
    production_companies: [
      { id: 501, logo_path: "/logos/epic_films.png", name: "Epic Films", origin_country: "US" },
      { id: 502, logo_path: null, name: "Global Pictures", origin_country: "UK" },
    ],
    production_countries: [
      { iso_3166_1: "US", name: "United States of America" },
      { iso_3166_1: "UK", name: "United Kingdom" },
    ],
    release_date: "2025-03-14",
    revenue: 350000000,
    runtime: 140,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "Humanity’s next leap.",
    title: "Shadows of Tomorrow",
    video: false,
    vote_average: 7.2,
    vote_count: 834,
  },
  {
    adult: false,
    backdrop_path: "/backdrops/whispering_winds.jpg",
    belongs_to_collection: null,
    budget: 30000000,
    genres: [
      { id: 18, name: "Drama" },
      { id: 10749, name: "Romance" },
    ],
    homepage: null,
    id: 1002,
    imdb_id: "tt1001002",
    original_language: "fr",
    original_title: "Les Vents Murmurants",
    overview: "A love story carried by the wind across continents.",
    popularity: 29.9,
    poster_path: "/posters/whispering_winds.jpg",
    production_companies: [
      { id: 503, logo_path: "/logos/romance_studio.png", name: "Romance Studio", origin_country: "FR" },
    ],
    production_countries: [
      { iso_3166_1: "FR", name: "France" },
    ],
    release_date: "2024-11-22",
    revenue: 95000000,
    runtime: 115,
    spoken_languages: [
      { english_name: "French", iso_639_1: "fr", name: "Français" },
    ],
    status: "Released",
    tagline: "Love carried by the wind.",
    title: "Whispering Winds",
    video: false,
    vote_average: 6.8,
    vote_count: 412,
  },
  {
    adult: false,
    backdrop_path: "/backdrops/cyber_siege.jpg",
    belongs_to_collection: {
      id: 3002,
      name: "Cyber Universe Series",
      poster_path: "/collections/cyber_universe.jpg",
      backdrop_path: "/collections/backdrop_cyber_universe.jpg",
    },
    budget: 80000000,
    genres: [
      { id: 28, name: "Action" },
      { id: 53, name: "Thriller" },
    ],
    homepage: "https://cyber-siege.example.com",
    id: 1003,
    imdb_id: "tt1001003",
    original_language: "en",
    original_title: "Cyber Siege",
    overview: "A hacker-turned-hero must defend the city from digital destruction.",
    popularity: 74.1,
    poster_path: "/posters/cyber_siege.jpg",
    production_companies: [
      { id: 504, logo_path: "/logos/tech_film_co.png", name: "Tech Film Co.", origin_country: "US" },
      { id: 505, logo_path: null, name: "City Pictures Ltd.", origin_country: "CA" },
    ],
    production_countries: [
      { iso_3166_1: "US", name: "United States of America" },
      { iso_3166_1: "CA", name: "Canada" },
    ],
    release_date: "2025-01-10",
    revenue: 210000000,
    runtime: 128,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "Hack the system. Save the city.",
    title: "Cyber Siege",
    video: false,
    vote_average: 7.9,
    vote_count: 1023,
  },
  {
    adult: false,
    backdrop_path: "/backdrops/midnight_garden.jpg",
    belongs_to_collection: null,
    budget: 22000000,
    genres: [
      { id: 14, name: "Fantasy" },
      { id: 18, name: "Drama" },
    ],
    homepage: null,
    id: 1004,
    imdb_id: "tt1001004",
    original_language: "en",
    original_title: "Midnight Garden",
    overview: "In a secret garden at midnight, everything becomes possible.",
    popularity: 19.7,
    poster_path: "/posters/midnight_garden.jpg",
    production_companies: [
      { id: 506, logo_path: "/logos/fantasy_studios.png", name: "Fantasy Studios", origin_country: "US" },
    ],
    production_countries: [
      { iso_3166_1: "US", name: "United States of America" },
    ],
    release_date: "2023-09-05",
    revenue: 48000000,
    runtime: 102,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "Magic happens when night falls.",
    title: "Midnight Garden",
    video: false,
    vote_average: 6.2,
    vote_count: 274,
  },
  {
    adult: false,
    backdrop_path: "/backdrops/rogue_planet.jpg",
    belongs_to_collection: null,
    budget: 95000000,
    genres: [
      { id: 12, name: "Adventure" },
      { id: 878, name: "Science Fiction" },
    ],
    homepage: "https://rogueplanet.example.com",
    id: 1005,
    imdb_id: "tt1001005",
    original_language: "en",
    original_title: "Rogue Planet",
    overview: "Stranded on a wild planet, they fight for survival and hope.",
    popularity: 64.8,
    poster_path: "/posters/rogue_planet.jpg",
    production_companies: [
      { id: 507, logo_path: "/logos/space_films.png", name: "Space Films", origin_country: "US" },
    ],
    production_countries: [
      { iso_3166_1: "US", name: "United States of America" },
      { iso_3166_1: "AU", name: "Australia" },
    ],
    release_date: "2024-06-17",
    revenue: 180000000,
    runtime: 135,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "Survival in the unknown.",
    title: "Rogue Planet",
    video: false,
    vote_average: 7.4,
    vote_count: 689,
  },
  {
    adult: false,
    backdrop_path: "/backdrops/echoes_silence.jpg",
    belongs_to_collection: null,
    budget: 15000000,
    genres: [
      { id: 27, name: "Horror" },
      { id: 53, name: "Thriller" },
    ],
    homepage: null,
    id: 1006,
    imdb_id: "tt1001006",
    original_language: "en",
    original_title: "Echoes of Silence",
    overview: "A haunted house and the echoes that never leave.",
    popularity: 22.3,
    poster_path: "/posters/echoes_silence.jpg",
    production_companies: [
      { id: 508, logo_path: null, name: "Scare Productions", origin_country: "US" },
    ],
    production_countries: [
      { iso_3166_1: "US", name: "United States of America" },
    ],
    release_date: "2023-10-31",
    revenue: 32000000,
    runtime: 98,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "They never stop whispering.",
    title: "Echoes of Silence",
    video: false,
    vote_average: 6.1,
    vote_count: 311,
  },
  {
    adult: false,
    backdrop_path: "/backdrops/final_score.jpg",
    belongs_to_collection: null,
    budget: 40000000,
    genres: [
      { id: 35, name: "Comedy" },
      { id: 18, name: "Drama" },
    ],
    homepage: "https://finalscore.example.com",
    id: 1007,
    imdb_id: "tt1001007",
    original_language: "en",
    original_title: "The Final Score",
    overview: "One last game to win more than the championship.",
    popularity: 45.5,
    poster_path: "/posters/final_score.jpg",
    production_companies: [
      { id: 509, logo_path: "/logos/sports_films.png", name: "Sports Films Co.", origin_country: "US" },
    ],
    production_countries: [
      { iso_3166_1: "US", name: "United States of America" },
    ],
    release_date: "2025-04-20",
    revenue: 120000000,
    runtime: 112,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "Beyond the final whistle.",
    title: "The Final Score",
    video: false,
    vote_average: 7.0,
    vote_count: 523,
  },
  {
    adult: false,
    backdrop_path: "/backdrops/fire_ice.jpg",
    belongs_to_collection: {
      id: 3003,
      name: "Mythic Elements Trilogy",
      poster_path: "/collections/mythic_elements.jpg",
      backdrop_path: "/collections/backdrop_mythic_elements.jpg",
    },
    budget: 110000000,
    genres: [
      { id: 12, name: "Adventure" },
      { id: 14, name: "Fantasy" },
      { id: 10751, name: "Family" }
    ],
    homepage: "https://fireandice.example.com",
    id: 1008,
    imdb_id: "tt1001008",
    original_language: "en",
    original_title: "Fire & Ice",
    overview: "Mythical beasts clash in the frozen lands as fire rises.",
    popularity: 56.1,
    poster_path: "/posters/fire_ice.jpg",
    production_companies: [
      { id: 510, logo_path: "/logos/mythic_studios.png", name: "Mythic Studios", origin_country: "US" },
    ],
    production_countries: [
      { iso_3166_1: "US", name: "United States of America" },
    ],
    release_date: "2024-12-12",
    revenue: 250000000,
    runtime: 134,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "Fire rises. Ice endures.",
    title: "Fire & Ice",
    video: false,
    vote_average: 7.6,
    vote_count: 758,
  },
  {
    adult: true,
    backdrop_path: "/backdrops/urban_shadows.jpg",
    belongs_to_collection: null,
    budget: 18000000,
    genres: [
      { id: 80, name: "Crime" },
      { id: 53, name: "Thriller" },
    ],
    homepage: null,
    id: 1009,
    imdb_id: "tt1001009",
    original_language: "en",
    original_title: "Urban Shadows",
    overview: "Inside the crime-web of the city’s darkest corners.",
    popularity: 33.4,
    poster_path: "/posters/urban_shadows.jpg",
    production_companies: [
      { id: 511, logo_path: null, name: "Dark Lane Pictures", origin_country: "US" },
    ],
    production_countries: [
      { iso_3166_1: "US", name: "United States of America" },
    ],
    release_date: "2023-08-15",
    revenue: 54000000,
    runtime: 123,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "Every alley has a secret.",
    title: "Urban Shadows",
    video: false,
    vote_average: 5.9,
    vote_count: 210,
  },
  {
    adult: false,
    backdrop_path: "/backdrops/solar_dawn.jpg",
    belongs_to_collection: null,
    budget: 90000000,
    genres: [
      { id: 878, name: "Science Fiction" },
      { id: 28, name: "Action" },
    ],
    homepage: "https://solardawn.example.com",
    id: 1010,
    imdb_id: "tt1001010",
    original_language: "en",
    original_title: "Solar Dawn",
    overview: "A new era begins as the sun rises on a distant world.",
    popularity: 68.2,
    poster_path: "/posters/solar_dawn.jpg",
    production_companies: [
      { id: 512, logo_path: "/logos/galactic_pictures.png", name: "Galactic Pictures", origin_country: "US" },
    ],
    production_countries: [
      { iso_3166_1: "US", name: "United States of America" },
      { iso_3166_1: "KR", name: "South Korea" },
    ],
    release_date: "2024-02-22",
    revenue: 300000000,
    runtime: 138,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "Beyond the dawn.",
    title: "Solar Dawn",
    video: false,
    vote_average: 7.5,
    vote_count: 845,
  }
];
